import { Component, OnInit, signal, computed } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { ApiService } from '../../../core/api.service';
import { AuthService } from '../../../core/auth.service';
import { Employee } from '../../../core/models';
import { PhoneMaskDirective } from '../../../core/phone-mask.directive';
import { FieldErrorComponent } from '../../../shared/field-error.component';

@Component({
  selector: 'app-employees',
  imports: [FormsModule, PhoneMaskDirective, FieldErrorComponent],
  templateUrl: './employees.component.html',
})
export class EmployeesComponent implements OnInit {
  readonly items = signal<Employee[]>([]);
  readonly roles = signal<{ role_id: number; role_name: string }[]>([]);
  readonly loading = signal(true);
  readonly showForm = signal(false);
  readonly saving = signal(false);
  readonly editingId = signal<number | null>(null);
  readonly search = signal('');
  readonly confirmTarget = signal<Employee | null>(null);
  // After creating an employee we surface the auto-generated temporary password
  // once, so the admin can copy it and hand it over.
  readonly createdCredentials = signal<{ name: string; password: string } | null>(null);
  readonly copied = signal(false);

  // True while the form being edited is the logged-in user's own row — used to
  // disable the role select so an admin can't demote/promote themselves.
  readonly editingIsSelf = computed(() => this.editingId() === this.auth.user()?.employee_id);

  filtered = computed(() => {
    const q = this.search().toLowerCase();
    if (!q) return this.items();
    return this.items().filter(
      (e) =>
        e.name.toLowerCase().includes(q) ||
        (e.role_name || '').toLowerCase().includes(q) ||
        (e.email || '').toLowerCase().includes(q) ||
        (e.phone || '').includes(q),
    );
  });

  form = this.empty();

  constructor(
    private readonly api: ApiService,
    private readonly auth: AuthService,
  ) {}

  ngOnInit(): void {
    this.reload();
    this.api.roles().subscribe((r) => this.roles.set(r.roles));
  }

  reload(): void {
    this.loading.set(true);
    this.api.employees().subscribe({
      next: (r) => {
        this.items.set(r.employees);
        this.loading.set(false);
      },
      error: () => this.loading.set(false),
    });
  }

  // True when the row belongs to the logged-in user (can't deactivate self).
  isSelf(e: Employee): boolean {
    return e.employee_id === this.auth.user()?.employee_id;
  }

  startEdit(e: Employee): void {
    this.editingId.set(e.employee_id);
    const role = this.roles().find((r) => r.role_name === e.role_name);
    this.form = {
      roleId: role?.role_id ?? null,
      name: e.name,
      email: e.email || '',
      phone: e.phone || '',
    };
    this.showForm.set(true);
  }

  cancelForm(): void {
    this.showForm.set(false);
    this.editingId.set(null);
    this.form = this.empty();
  }

  save(): void {
    this.saving.set(true);
    const editing = this.editingId();
    // On edit only data is updated (name, role, email, phone). On create the
    // login password is auto-generated by the backend and returned once so we
    // can show it in the credentials modal.
    if (editing) {
      this.api
        .updateEmployee(editing, {
          roleId: this.form.roleId,
          name: this.form.name,
          email: this.form.email,
          phone: this.form.phone,
        })
        .subscribe({
          next: () => {
            this.saving.set(false);
            this.cancelForm();
            this.reload();
          },
          error: () => this.saving.set(false),
        });
      return;
    }

    const name = this.form.name;
    this.api.createEmployee(this.form).subscribe({
      next: (res) => {
        this.saving.set(false);
        this.cancelForm();
        this.reload();
        const tempPassword = (res as { tempPassword?: string }).tempPassword;
        if (tempPassword) {
          this.copied.set(false);
          this.createdCredentials.set({ name, password: tempPassword });
        }
      },
      error: () => this.saving.set(false),
    });
  }

  copyPassword(): void {
    const password = this.createdCredentials()?.password;
    if (!password) return;
    navigator.clipboard.writeText(password).then(() => {
      this.copied.set(true);
      setTimeout(() => this.copied.set(false), 2000);
    });
  }

  closeCredentials(): void {
    this.createdCredentials.set(null);
    this.copied.set(false);
  }

  confirmDeactivate(e: Employee): void {
    this.confirmTarget.set(e);
  }

  cancelConfirm(): void {
    this.confirmTarget.set(null);
  }

  deactivate(): void {
    const e = this.confirmTarget();
    if (!e) return;
    this.confirmTarget.set(null);
    this.api.deleteEmployee(e.employee_id).subscribe({
      next: () => this.reload(),
    });
  }

  activate(e: Employee): void {
    this.api.updateEmployee(e.employee_id, { status: true }).subscribe({
      next: () => this.reload(),
    });
  }

  private empty() {
    return { roleId: null as number | null, name: '', email: '', phone: '' };
  }
}
